name: yarn install
description: yarn install
inputs:
  ls_options:
    description: ls options
    required: false
    # in windows, la does NOT work
    default: "-la"

  working-directory:
    description: working-directory
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: ls
      shell: bash
      run: ls ${{ inputs.ls_options }} ${{ inputs.working-directory }}

    - name: npm run setup:ci
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      # run: yarn run setup:ci --if-present # FIXME this fails
      run: npm run setup:ci --if-present # XXX

    - name: yarn install
      shell: bash
      run: yarn install --frozen-lockfile --cwd ${{ inputs.working-directory }}

    - name: ls ./node_modules
      shell: bash
      run: ls ${{ inputs.ls_options }} ${{ inputs.working-directory }}/node_modules
