name: yarn install
description: yarn install
inputs:
  ls_options:
    description: ls options
    required: false
    # in windows, la does NOT work
    default: "-la"

  working-directory:
    description: working-directory
    required: false
    default: "."

  script_preinstall:
    description: preinstall
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: ls
      shell: bash
      run: ls ${{ inputs.ls_options }} ${{ inputs.working-directory }}

    - name: yarn run setup:ci
      if: ${{ inputs.script_preinstall }} != ""
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      # NOTE: "npm run foo --if-present" does work
      # BUT "yarn run foo --if-present" does NOT work
      run: yarn run ${{ inputs.script_preinstall }}

    - name: rm -rf ./node_modules
      shell: bash
      run: rm -rf ${{ inputs.working-directory }}/node_modules

    - name: yarn install
      shell: bash
      run: yarn install --frozen-lockfile --cwd ${{ inputs.working-directory }}

    - name: ls ./node_modules
      shell: bash
      run: ls ${{ inputs.ls_options }} ${{ inputs.working-directory }}/node_modules
