name: "[C]ontinuous [I]ntegration"
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  lint:
    uses: ./.github/workflows/run_script.yml
    with:
      script: lint
