name: cmd run
on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    inputs:
      runs-on:
        type: string
        description: The type of machine to run on
        required: false
        default: ubuntu-latest

      working-directory:
        type: string
        description: working-directory
        required: false
        default: "."

      cmd:
        type: string
        description: The bash command to run.
        required: false
        default: yarn test

jobs:
  cmd_run:
    name: ${{ inputs.cmd }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-node/.github/actions/node_setup@main
      - uses: percebus/github-actions-yarn/.github/actions/yarn_install@main
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: ${{ inputs.cmd }}
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.cmd }}
