name: yarn run script
on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    inputs:
      runs-on:
        type: string
        description: The type of machine to run on
        required: false
        default: ubuntu-latest

      ssh-private-key:
        type: string
        description: SSH private key
        required: false

      working-directory:
        type: string
        description: working-directory
        required: false
        default: "."

      script:
        type: string
        description: The yarn script to run.
        required: false
        default: test

# concurrency:
#   group: ${{ github.ref }}-${{ github.workflow }}
#   cancel-in-progress: true

jobs:
  yarn_run_script:
    name: yarn run ${{ inputs.script }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ssh-private-key: ${{ inputs.ssh-private-key }}

      - uses: percebus/github-actions-node/.github/actions/setup@main
      - uses: percebus/github-actions-yarn/.github/actions/install@main
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: yarn run ${{ inputs.script }}
        # NOTE: --cwd not working
        working-directory: ${{ inputs.working-directory }}
        run: yarn run ${{ inputs.script }}
