name: Test workflows/run_cmd
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  default:
    name: default
    uses: ./.github/workflows/run_cmd.yml

  cmd__matrix:
    needs: default
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        cmd:
          - yarn test
          - yarn test --ignore-scripts
          - yarn lint
          - echo bananas

    name: "cmd: '${{ matrix.cmd }}'"
    uses: ./.github/workflows/run_cmd.yml
    with:
      cmd: ${{ matrix.cmd }}

  os__matrix:
    needs: default
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        OS:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    name: "@ ${{ matrix.OS }}"
    uses: ./.github/workflows/run_cmd.yml
    with:
      cmd: echo "bananas"
      runs-on: ${{ matrix.OS }}
