name: workflows/cmd_run
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  cmd_matrix:
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        cmd:
          - yarn test
          - yarn test --ignore-scripts
          - yarn lint
          - echo bananas

    uses: ./.github/workflows/cmd_run.yml
    with:
      cmd: ${{ matrix.cmd }}

  os_matrix:
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        OS:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    uses: ./.github/workflows/cmd_run.yml
    with:
      cmd: yarn test --ignore-scripts
      runs-on: ${{ matrix.OS }}
