name: Test actions/yarn_install
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  default:
    name: default
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-node/.github/actions/setup@main
      - uses: ./.github/actions/yarn_install

  ls_options:
    needs: default
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        ls_options:
          - "-la"
          - "-l"
          - "-a"
        OS:
          - ubuntu-latest
          - macos-latest
        include:
          - OS: windows-latest
            ls_options: ""

    runs-on: ${{ matrix.OS }}
    name: ls ${{ matrix.ls_options }} @ ${{ matrix.OS }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-node/.github/actions/setup@main
      - uses: ./.github/actions/yarn_install
        with:
          ls_options: ${{ matrix.ls_options }}
