name: Test workflows/run_script
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  default:
    name: default
    uses: ./.github/workflows/run_script.yml

  script__matrix:
    needs: default
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        script:
          - test
          - lint

    name: "script: ${{ matrix.script }}"
    uses: ./.github/workflows/run_script.yml
    with:
      script: ${{ matrix.script }}

  os__matrix:
    needs: default
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        OS:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    name: "@ ${{ matrix.OS }}"
    uses: ./.github/workflows/run_script.yml
    with:
      # windows complains about EoL characters in the script
      script: style
      runs-on: ${{ matrix.OS }}
