name: yarn run script
on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    inputs:
      runs-on:
        type: string
        description: The type of machine to run on
        required: false
        default: ubuntu-latest

      working-directory:
        type: string
        description: working-directory
        required: false
        default: "."

      script:
        type: string
        description: The yarn script to run.
        required: false
        default: test

jobs:
  yarn_run:
    name: yarn run ${{ inputs.script }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-node/.github/actions/node_setup@main
      - uses: percebus/github-actions-yarn/.github/actions/yarn_install@main
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: yarn run ${{ inputs.script }}
        # NOTE: --cwd not working
        working-directory: ${{ inputs.working-directory }}
        run: yarn run ${{ inputs.script }}
